name: ci

on:
  push:
    branches:
      - 'deployment'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
#       - 
#         name: test
#         run: docker-compose up --exit-code-from api
#         shell: bash
#         env:
#           SECRET: ${secrets.SECRET}
#           CLOUDINARY_CLOUD_NAME: ${secrets.CLOUDINARY_CLOUD_NAME}
#           CLOUDINARY_API_KEY: ${secrets.CLOUDINARY_API_KEY}
#           CLOUDINARY_API_SECRET: ${secrets.CLOUDINARY_API_SECRET}
#           GOOGLE_CLIENT_ID: ${secrets.GOOGLE_CLIENT_ID}
#           GOOGLE_CLIENT_SECRET: ${secrets.GOOGLE_CLIENT_SECRET}
#           AUTH_EMAIL: ${secrets.AUTH_EMAIL}
#           AUTH_PASS: ${secrets.AUTH_PASS}
#           CURRENTURL: http://localhost:3000/
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Push old version to old image
        run: |
          docker pull mostafaelnashar/larry-api:latest
          docker tag mostafaelnashar/larry-api:latest mostafaelnashar/larry-api:old
          docker push mostafaelnashar/larry-api:old
          docker pull mostafaelnashar/larry-router:latest
          docker tag mostafaelnashar/larry-router:latest mostafaelnashar/larry-router:old
          docker push mostafaelnashar/larry-router:old
          docker pull mostafaelnashar/larry-client:latest
          docker tag mostafaelnashar/larry-client:latest mostafaelnashar/larry-client:old
          docker push mostafaelnashar/larry-client:old

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./client
          push: true
          tags: mostafaelnashar/larry-client:latest
      
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: mostafaelnashar/larry-api:latest
          
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./router
          push: true
          tags: mostafaelnashar/larry-router:latest
      -     
        name: Deploy to AWS Elastic Beanstalk
        uses: Amraneze/aws-beanstalk-deploy@master
        with:
          region: us-east-1
          environment_name: Larry-env
          application_name: Larry
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          s3_bucket_name: elasticbeanstalk-us-east-1-284489073366
          s3_file_path: \larry
          ebs_wait_for_env_to_be_green: true
          ebs_version_label: ${{ github.event.repository.updated_at}}
